language: php

sudo: false

php:
 - 7.1
 - 7.2

env:
  - SHARIFF_RUN_LINT=1
  - SHARIFF_RUN_TEST=1

before_script:
 - bash -c 'if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;'
 - bash -c 'if [ -n "$SHARIFF_RUN_TEST" ]; then composer install --prefer-dist --no-interaction; fi;'
 - bash -c 'if [ -n "$SHARIFF_RUN_LINT" ]; then composer require "squizlabs/php_codesniffer=*"; fi;'
 - bash -c 'if [ -n "$SHARIFF_RUN_LINT" ]; then composer require friendsofphp/php-cs-fixer --dev; fi;'

script:
 - bash -c 'if [ -n "$SHARIFF_RUN_LINT" ]; then vendor/bin/phpcs --standard=PSR2 src/ tests/; fi;'
 - bash -c 'if [ -n "$SHARIFF_RUN_LINT" ]; then make cs_dry_run; fi;'
 - bash -c 'if [ -n "$SHARIFF_RUN_TEST" ]; then vendor/bin/phpunit --coverage-text; fi;'

addons:
 apt:
  packages:
   - p7zip-full

before_deploy:
 - bash build.sh
 - 7z a -tzip shariff-backend-php.zip ./build/*
 - 7z a -ttar -so shariff-backend-php.tar ./build/* | 7z a -si shariff-backend-php.tar.gz

deploy:
  provider: releases
  api_key:
    secure: jbEPfD2xopoDQBGTJsrGvwhvb5MZislQowvHtsJ7f+B9seS9FGVc8Yq2kcqGX+8I8DyI5RCu3UlorGVnOQrxT9yxHVEK8PGjqOSCgRZw8p3jZmoNzrN7Qi+5YjCXxrAEKbT0nFYvis1DJqbuLOOU9+DBP6JWKmYvrtCjNSIxRIY=
  file:
   - shariff-backend-php.zip
   - shariff-backend-php.tar.gz
  skip_cleanup: true
  on:
    repo: heiseonline/shariff-backend-php
    tags: true
    php: 7.1
    condition: $SHARIFF_RUN_TEST = 1
